/// <reference types="@remix-run/dev" />
/// <reference types="@remix-run/node/globals" />

import type { AssetsManifest } from "@remix-run/server-runtime/dist/entry";
import type {
  EntryRouteModule,
  RouteModules,
} from "@remix-run/server-runtime/dist/routeModules";

declare module "@remix-run/server-runtime" {
  interface AppLoadContext {
    netlifyGraphToken?: string; // raw authentication token to use with Netlify Graph
    clientNetlifyGraphAccessToken?: string; // For use with JWTs generated by `netlify-graph-auth`.
    netlifyGraphSignature?: string; // a signature for subscription events. Will be present if a secret is set.
    routeModules: RouteModules<EntryRouteModule>;
    manifest: AssetsManifest;
  }
}
